# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "75434c1dcf87415a758a5551a63cbf54"
name = "LocaleMate"
application_url = "https://locale-mate.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://locale-mate.vercel.app/webhooks/customers/redact"
  customer_data_request_url = "https://locale-mate.vercel.app/webhooks/customers/data_request"
  shop_deletion_url = "https://locale-mate.vercel.app/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales,read_markets,read_translations,write_locales,write_translations"

[auth]
redirect_urls = [
  "https://locale-mate.vercel.app/auth/callback",
  "https://locale-mate.vercel.app/auth/shopify/callback",
  "https://locale-mate.vercel.app/api/auth/callback"
]
